# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.srcs/sources_1/bd/inclinometer/ip/inclinometer_xbar_2/inclinometer_xbar_2.xci
# IP: The module: 'inclinometer_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.gen/sources_1/bd/inclinometer/ip/inclinometer_xbar_2/inclinometer_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inclinometer_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.srcs/sources_1/bd/inclinometer/ip/inclinometer_xbar_2/inclinometer_xbar_2.xci
# IP: The module: 'inclinometer_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.gen/sources_1/bd/inclinometer/ip/inclinometer_xbar_2/inclinometer_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inclinometer_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
