# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.srcs/sources_1/bd/inclinometer/ip/inclinometer_microblaze_0_axi_intc_1/inclinometer_microblaze_0_axi_intc_1.xci
# IP: The module: 'inclinometer_microblaze_0_axi_intc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.gen/sources_1/bd/inclinometer/ip/inclinometer_microblaze_0_axi_intc_1/inclinometer_microblaze_0_axi_intc_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'inclinometer_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.gen/sources_1/bd/inclinometer/ip/inclinometer_microblaze_0_axi_intc_1/inclinometer_microblaze_0_axi_intc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'inclinometer_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.gen/sources_1/bd/inclinometer/ip/inclinometer_microblaze_0_axi_intc_1/inclinometer_microblaze_0_axi_intc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inclinometer_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.srcs/sources_1/bd/inclinometer/ip/inclinometer_microblaze_0_axi_intc_1/inclinometer_microblaze_0_axi_intc_1.xci
# IP: The module: 'inclinometer_microblaze_0_axi_intc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.gen/sources_1/bd/inclinometer/ip/inclinometer_microblaze_0_axi_intc_1/inclinometer_microblaze_0_axi_intc_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'inclinometer_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.gen/sources_1/bd/inclinometer/ip/inclinometer_microblaze_0_axi_intc_1/inclinometer_microblaze_0_axi_intc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'inclinometer_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/Inclinometer/Inclinometer.gen/sources_1/bd/inclinometer/ip/inclinometer_microblaze_0_axi_intc_1/inclinometer_microblaze_0_axi_intc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inclinometer_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
