# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/rvfpganexys.xdc

# Block Designs: bd/inclinometer/inclinometer.bd
# Block Designs: The module: 'inclinometer' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/inclinometer/ip/inclinometer_xbar_2/inclinometer_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_xbar_2 || ORIG_REF_NAME==inclinometer_xbar_2} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_microblaze_0_axi_periph_1/inclinometer_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_microblaze_0_axi_periph_1 || ORIG_REF_NAME==inclinometer_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_microblaze_0_axi_intc_1/inclinometer_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_microblaze_0_axi_intc_1 || ORIG_REF_NAME==inclinometer_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_microblaze_0_xlconcat_1/inclinometer_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_microblaze_0_xlconcat_1 || ORIG_REF_NAME==inclinometer_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_mdm_1_1/inclinometer_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_mdm_1_1 || ORIG_REF_NAME==inclinometer_mdm_1_1} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_clk_wiz_1_0/inclinometer_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_clk_wiz_1_0 || ORIG_REF_NAME==inclinometer_clk_wiz_1_0} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_rst_clk_wiz_1_100M_0/inclinometer_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==inclinometer_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_axi_timer_0_1/inclinometer_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_axi_timer_0_1 || ORIG_REF_NAME==inclinometer_axi_timer_0_1} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_axi_uartlite_0_0/inclinometer_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_axi_uartlite_0_0 || ORIG_REF_NAME==inclinometer_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_nexys4io_0_2/inclinometer_nexys4io_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_nexys4io_0_2 || ORIG_REF_NAME==inclinometer_nexys4io_0_2} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_axi_iic_0_1/inclinometer_axi_iic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_axi_iic_0_1 || ORIG_REF_NAME==inclinometer_axi_iic_0_1} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_microblaze_0_3/inclinometer_microblaze_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_microblaze_0_3 || ORIG_REF_NAME==inclinometer_microblaze_0_3} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_dlmb_v10_3/inclinometer_dlmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_dlmb_v10_3 || ORIG_REF_NAME==inclinometer_dlmb_v10_3} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_ilmb_v10_3/inclinometer_ilmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_ilmb_v10_3 || ORIG_REF_NAME==inclinometer_ilmb_v10_3} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_dlmb_bram_if_cntlr_3/inclinometer_dlmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==inclinometer_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_ilmb_bram_if_cntlr_3/inclinometer_ilmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==inclinometer_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_lmb_bram_3/inclinometer_lmb_bram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_lmb_bram_3 || ORIG_REF_NAME==inclinometer_lmb_bram_3} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_bidirec_0_0/inclinometer_bidirec_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_bidirec_0_0 || ORIG_REF_NAME==inclinometer_bidirec_0_0} -quiet] -quiet

# IP: bd/inclinometer/ip/inclinometer_bidirec_1_0/inclinometer_bidirec_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inclinometer_bidirec_1_0 || ORIG_REF_NAME==inclinometer_bidirec_1_0} -quiet] -quiet

# XDC: c:/Users/jadha/OneDrive/Desktop/TA/ECE544-Winter24/github_repo/Inclinometer/Inclinometer/Inclinometer.gen/sources_1/bd/inclinometer/inclinometer_ooc.xdc
